/** 集市商品审计日志动作类型（与 Prisma MarketLogActionType 枚举一致） */
export const MarketLogActionType = {
  INTENTION_CREATED: "INTENTION_CREATED",
  INTENTION_WITHDRAWN: "INTENTION_WITHDRAWN",
  ITEM_LOCKED: "ITEM_LOCKED",
  ITEM_UNLOCKED: "ITEM_UNLOCKED",
  INTENTION_RESET_BY_UNLOCK: "INTENTION_RESET_BY_UNLOCK",
  INTENTION_AUTO_WITHDRAWN_ON_UNLOCK: "INTENTION_AUTO_WITHDRAWN_ON_UNLOCK",
  TRANSACTION_COMPLETED: "TRANSACTION_COMPLETED",
  BUYER_CONFIRMED: "BUYER_CONFIRMED",
  SELLER_CONFIRMED: "SELLER_CONFIRMED",
  ITEM_EDITED: "ITEM_EDITED",
  ADMIN_HIDDEN: "ADMIN_HIDDEN",
  ADMIN_RELISTED: "ADMIN_RELISTED",
  ITEM_DELETED: "ITEM_DELETED",
  AUTO_UNLOCKED: "AUTO_UNLOCKED",
  AUTO_COMPLETED: "AUTO_COMPLETED",
} as const;

/** 审计日志动作类型 → 可读标签 */
export const MARKET_LOG_ACTION_LABELS: Record<string, string> = {
  INTENTION_CREATED: "提交意向",
  INTENTION_WITHDRAWN: "撤回意向",
  ITEM_LOCKED: "锁定商品",
  ITEM_UNLOCKED: "解锁商品",
  INTENTION_RESET_BY_UNLOCK: "意向重置（解锁）",
  INTENTION_AUTO_WITHDRAWN_ON_UNLOCK: "意向自动撤回（解锁）",
  TRANSACTION_COMPLETED: "交易完成",
  BUYER_CONFIRMED: "买家确认",
  SELLER_CONFIRMED: "卖家确认",
  ITEM_EDITED: "编辑商品",
  ADMIN_HIDDEN: "管理员下架",
  ADMIN_RELISTED: "管理员重新上架",
  ITEM_DELETED: "删除商品",
  AUTO_UNLOCKED: "自动解锁",
  AUTO_COMPLETED: "自动完成",
};

export const AUTO_UNLOCK_HOURS = 48;
export const AUTO_COMPLETE_HOURS = 24;

/** 集市/留言 举报阈值常量（与 PRD R31/R15 一致） */
export const REPORT_AUDIT_THRESHOLD = 3;   // 举报 3 次 → 进入管理员审核列表
export const REPORT_HIDE_THRESHOLD = 5;     // 举报 5 次 → 自动隐藏
